# Generated by Django 5.1.4 on 2025-04-28 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=200)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investments_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('savings_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('investments_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('savings_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('is_credit', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('financial_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.financialrecord')),
            ],
        ),
    ]
